tunnel: platos-cave-api
credentials-file: /home/jackiecourtney/.cloudflared/platos-cave-api.json

ingress:
  - hostname: api.jackie-courtney.com
    service: http://localhost:5001
  - hostname: browser.jackie-courtney.com
    service: http://localhost:7900
  - service: http_status:404